# Generated by Django 2.2.7 on 2019-11-10 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'movies',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('seat_no', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'seats',
                'verbose_name_plural': 'Seats',
            },
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.DateTimeField()),
                ('screen', models.CharField(max_length=15)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='showapi.Movies')),
                ('seats', models.ManyToManyField(to='showapi.Seats')),
            ],
            options={
                'db_table': 'shows',
                'verbose_name_plural': 'Shows',
            },
        ),
    ]
